GET http://localhost:3000/userapi/users

###
POST http://localhost:3000/userapi/new-user
Content-Type: application/json

{
    "username":"user2",
    "rollno":"22071a05a5",
    "branch":"cse",
    "email":"user1@gmail.com",
    "password":"user1"
}